!
)
:
evaluated
outer
finally
block
)
:
evaluated
inner
finally
block
)
:
evaluated
outer
catch
block
336872
BUGNUMBER
ECMA_2
FAIL
:
DID
NOT
HIT
INNER
FINALLY
BLOCK
FAIL
:
DID
NOT
HIT
OUTER
FINALLY
BLOCK
FAIL
:
HIT
OUTER
CATCH
BLOCK
FAILED
:
NO
EXCEPTION
CAUGHT
PASS
SECTION
TITLE
TestCase
The
try
statement
TrySomething
VERSION
e
eval
eval
(
expression
innerFinally
outerCatch
outerFinally
startTest
test
throw
"
boo
"
throw
3
throwing
try
-
012
writeHeaderToLog
x
=
"
hi
"
|
3
]
}
'
m
R
R
R
w
s
c
g
Q
6
